name: Maven Release

on:
  workflow_dispatch:
    inputs:
      next-release-version:
        description: 'Next Release Version'
      next-snapshot-version:
        description: 'Next Snapshot Version'

jobs:
  call-workflow:
    uses: emergentdotorg/github-actions/.github/workflows/reusable-maven-release.yml@main
    with:
      java-version: '8'
      next-release-version: ${{ inputs.next-release-version }}
      next-snapshot-version: ${{ inputs.next-snapshot-version }}
    secrets: inherit
